name: Testing
on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node.js environment ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Run format validation
        run: npm run format
      - name: Run linter validation
        run: npm run lint
      - name: Run unit tests
        run: npm test
